version: '3.8'

services:
  api:
    build:
      context: ./spotify_api
    ports:
      - "3000:3000"
    volumes:
      - ./spotify_api:/usr/src/app
    environment:
      - NODE_ENV=development

  app:
    build:
      context: ./spotify_app
    ports:
      - "3001:80" # Mapper le port 3001 vers 80 pour nginx
    depends_on:
      - api
